version: '3.8'

services:
  rabbitmq:
    build:
      context: ./rabbitmq
    container_name: currency-gateway-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-gateway}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-gateway}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-/}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
    driver: local
